name: Build and Publish NuGet

on:
  push:
    branches:
      - master # or whichever branch you want to trigger from

jobs:
  build:
    runs-on: ubuntu-latest # or ubuntu-latest with .NET Core SDK installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack --no-build -c Release -o out

    - name: Push to NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: HCQR/HCQR.csproj # for example: src/YourProject/YourProject.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

