name: Build and Publish NuGet

on:
  push:
    branches:
      - master # or whichever branch you want to trigger from

jobs:
  build:
    runs-on: ubuntu-latest # or ubuntu-latest with .NET Core SDK installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Version
      id: generate_version
      run: |
        MAJOR=1
        BUILD=$(( GITHUB_RUN_NUMBER ))
        REVISION=$(( $(git rev-list --count HEAD) ))
        VERSION="$MAJOR.$BUILD.$REVISION"
        echo "Generated Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${{ env.VERSION }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output . /p:Version=${{ env.VERSION }}
      
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

